; ============================================================================================
; LUMINARY - a game engine and framework for the SEGA Mega Drive
; ============================================================================================
; Matt Phillips - Big Evil Corporation Ltd - 22nd December 2025
; ============================================================================================
; PALWHITE.ASM - White palette
; ============================================================================================
    
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE

    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE

    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE

    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE
    dc.w   0x0EEE