// ============================================================================================
//   AUTOGENERATED WITH BEEHIVE - DO NOT EDIT MANUALLY
// ============================================================================================
//   http://www.bigevilcorporation.co.uk
// ============================================================================================
//   Beehive and LUMINARY Engine (c) Matt Phillips 2020
// ============================================================================================


#include <Common.h>
#include <Components.h>

struct EMotobug : Entity
{
	struct Components
	{
		ComponentHndl sprite;
		ComponentHndl sprite2;
		ComponentHndl enemy;
		ComponentHndl script;
	};

	short idleTimer;
	short velX;

	Components components;

	void OnStart(const Engine& engine, const Scene& scene);
	void OnShutdown(const Engine& engine, const Scene& scene);
	void OnUpdate(const Engine& engine, const Scene& scene);
};
