// ============================================================================================
//   AUTOGENERATED WITH BEEHIVE - DO NOT EDIT MANUALLY
// ============================================================================================
//   http://www.bigevilcorporation.co.uk
// ============================================================================================
//   Beehive and LUMINARY Engine (c) Matt Phillips 2020
// ============================================================================================


#include <Common.h>
#include <Components.h>

struct EPlayer : Entity
{
	struct Components
	{
		ComponentHndl physBodyChar;
		ComponentHndl sprite;
		ComponentHndl script;
	};

	short terrainFlagsPrev;
	char stateFlags;
	unsigned char padding;

	Components components;

	void OnStart(const Engine& engine, const Scene& scene);
	void OnShutdown(const Engine& engine, const Scene& scene);
	void OnUpdate(const Engine& engine, const Scene& scene);
};
